//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Case
    {
        public int c_id { get; set; }
        public Nullable<int> t_id { get; set; }
        public Nullable<int> p_id { get; set; }
        public Nullable<int> rb_id { get; set; }
        public Nullable<int> st_id { get; set; }
        public Nullable<int> com_id { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public Nullable<System.DateTime> viol_date { get; set; }
    }
}
